### PR TITLE
Depend on the Swagger Plugin rather than including it.

### PR DESCRIPTION
**Pull request by joeljons**
Avoid problems like this:
duplicate importers

If not installed already the Swagger Plugin will be installed when the SwaggerHub Plugin is installed.

### CODE REVIEW

**Comment by spindelmanne** [comment]
Good catch. I don't think it will make a difference for SoapUI OS, but it will for Ready! API.

**Comment by olensmar** [comment]
Very cool - I didn't know about this @PluginDependency annotation - thanks for pointing it out!

**Comment by olensmar** [comment]
@spindelmanne  @joeljons perhaps we need to add a min-version attribute to the plugin itself - since the plugindependency stuff was introduced after R!A 1.0?

**Comment by spindelmanne** [comment]
Maybe, but not very important because I think it was introduced in 1.1.

**Comment by olensmar** [comment]
ok - i'll build a new version of the plugin and will ask Lorinda to publish... thanks!

**Pull request merged**
